[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pise"
version = "1.1.0"
description = "Pipeline for IS-Seq sequencing data analysis"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "biopython>=1.81",
    "pandas",
    "plotly",
    "pyfastx>=2.3.1",
    "pytest",
]

[project.scripts]
pise = "pise.main:main"
pise-preprocess = "pise.filter_reads:main"
