# IS-Seq Pipeline Configuration File

# Path to the primers database file
primers_file: "config/primers.fasta"

# Main pipeline output directory
output_dir: "results_asv"

# Preprocessing parameters
preprocessing:
  min_cov: 0.9
  min_identity: 0.9
  min_len: 20
  index_i5: true
  i5_mismatch: 2
  len_actual_primer: 20 # Set to integer to enable partial match, e.g. 20
  threads: 8 # Number of parallel processes to use for read filtering
  qc: true # Run QC and demultiplexing step on forward reads (default: true)

# Alignment parameters (for future implementation)
alignment:
  threads: 4
  bwa_mem2_path: "bwa-mem2"
